/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../pages/__root'
import { Route as CanvasRouteImport } from './../pages/_canvas'
import { Route as CanvasIndexRouteImport } from './../pages/_canvas/index'
import { Route as CanvasPlayShipRouteImport } from './../pages/_canvas/play/ship'
import { Route as CanvasPlaySelectShipRouteImport } from './../pages/_canvas/play/select-ship'
import { Route as CanvasPlaySelectRouteRouteImport } from './../pages/_canvas/play/select-route'
import { Route as CanvasPlayConfirmRouteRouteImport } from './../pages/_canvas/play/confirm-route'
import { Route as CanvasCodexUpgradesRouteImport } from './../pages/_canvas/codex/upgrades'
import { Route as CanvasCodexModulesIndexRouteImport } from './../pages/_canvas/codex/modules/index'
import { Route as CanvasCodexModulesModuleIdRouteImport } from './../pages/_canvas/codex/modules/$moduleId'

const CanvasRoute = CanvasRouteImport.update({
  id: '/_canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasIndexRoute = CanvasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CanvasRoute,
} as any)
const CanvasPlayShipRoute = CanvasPlayShipRouteImport.update({
  id: '/play/ship',
  path: '/play/ship',
  getParentRoute: () => CanvasRoute,
} as any)
const CanvasPlaySelectShipRoute = CanvasPlaySelectShipRouteImport.update({
  id: '/play/select-ship',
  path: '/play/select-ship',
  getParentRoute: () => CanvasRoute,
} as any)
const CanvasPlaySelectRouteRoute = CanvasPlaySelectRouteRouteImport.update({
  id: '/play/select-route',
  path: '/play/select-route',
  getParentRoute: () => CanvasRoute,
} as any)
const CanvasPlayConfirmRouteRoute = CanvasPlayConfirmRouteRouteImport.update({
  id: '/play/confirm-route',
  path: '/play/confirm-route',
  getParentRoute: () => CanvasRoute,
} as any)
const CanvasCodexUpgradesRoute = CanvasCodexUpgradesRouteImport.update({
  id: '/codex/upgrades',
  path: '/codex/upgrades',
  getParentRoute: () => CanvasRoute,
} as any)
const CanvasCodexModulesIndexRoute = CanvasCodexModulesIndexRouteImport.update({
  id: '/codex/modules/',
  path: '/codex/modules/',
  getParentRoute: () => CanvasRoute,
} as any)
const CanvasCodexModulesModuleIdRoute =
  CanvasCodexModulesModuleIdRouteImport.update({
    id: '/codex/modules/$moduleId',
    path: '/codex/modules/$moduleId',
    getParentRoute: () => CanvasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof CanvasIndexRoute
  '/codex/upgrades': typeof CanvasCodexUpgradesRoute
  '/play/confirm-route': typeof CanvasPlayConfirmRouteRoute
  '/play/select-route': typeof CanvasPlaySelectRouteRoute
  '/play/select-ship': typeof CanvasPlaySelectShipRoute
  '/play/ship': typeof CanvasPlayShipRoute
  '/codex/modules/$moduleId': typeof CanvasCodexModulesModuleIdRoute
  '/codex/modules/': typeof CanvasCodexModulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof CanvasIndexRoute
  '/codex/upgrades': typeof CanvasCodexUpgradesRoute
  '/play/confirm-route': typeof CanvasPlayConfirmRouteRoute
  '/play/select-route': typeof CanvasPlaySelectRouteRoute
  '/play/select-ship': typeof CanvasPlaySelectShipRoute
  '/play/ship': typeof CanvasPlayShipRoute
  '/codex/modules/$moduleId': typeof CanvasCodexModulesModuleIdRoute
  '/codex/modules': typeof CanvasCodexModulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_canvas': typeof CanvasRouteWithChildren
  '/_canvas/': typeof CanvasIndexRoute
  '/_canvas/codex/upgrades': typeof CanvasCodexUpgradesRoute
  '/_canvas/play/confirm-route': typeof CanvasPlayConfirmRouteRoute
  '/_canvas/play/select-route': typeof CanvasPlaySelectRouteRoute
  '/_canvas/play/select-ship': typeof CanvasPlaySelectShipRoute
  '/_canvas/play/ship': typeof CanvasPlayShipRoute
  '/_canvas/codex/modules/$moduleId': typeof CanvasCodexModulesModuleIdRoute
  '/_canvas/codex/modules/': typeof CanvasCodexModulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/codex/upgrades'
    | '/play/confirm-route'
    | '/play/select-route'
    | '/play/select-ship'
    | '/play/ship'
    | '/codex/modules/$moduleId'
    | '/codex/modules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/codex/upgrades'
    | '/play/confirm-route'
    | '/play/select-route'
    | '/play/select-ship'
    | '/play/ship'
    | '/codex/modules/$moduleId'
    | '/codex/modules'
  id:
    | '__root__'
    | '/_canvas'
    | '/_canvas/'
    | '/_canvas/codex/upgrades'
    | '/_canvas/play/confirm-route'
    | '/_canvas/play/select-route'
    | '/_canvas/play/select-ship'
    | '/_canvas/play/ship'
    | '/_canvas/codex/modules/$moduleId'
    | '/_canvas/codex/modules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CanvasRoute: typeof CanvasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_canvas': {
      id: '/_canvas'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_canvas/': {
      id: '/_canvas/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof CanvasIndexRouteImport
      parentRoute: typeof CanvasRoute
    }
    '/_canvas/play/ship': {
      id: '/_canvas/play/ship'
      path: '/play/ship'
      fullPath: '/play/ship'
      preLoaderRoute: typeof CanvasPlayShipRouteImport
      parentRoute: typeof CanvasRoute
    }
    '/_canvas/play/select-ship': {
      id: '/_canvas/play/select-ship'
      path: '/play/select-ship'
      fullPath: '/play/select-ship'
      preLoaderRoute: typeof CanvasPlaySelectShipRouteImport
      parentRoute: typeof CanvasRoute
    }
    '/_canvas/play/select-route': {
      id: '/_canvas/play/select-route'
      path: '/play/select-route'
      fullPath: '/play/select-route'
      preLoaderRoute: typeof CanvasPlaySelectRouteRouteImport
      parentRoute: typeof CanvasRoute
    }
    '/_canvas/play/confirm-route': {
      id: '/_canvas/play/confirm-route'
      path: '/play/confirm-route'
      fullPath: '/play/confirm-route'
      preLoaderRoute: typeof CanvasPlayConfirmRouteRouteImport
      parentRoute: typeof CanvasRoute
    }
    '/_canvas/codex/upgrades': {
      id: '/_canvas/codex/upgrades'
      path: '/codex/upgrades'
      fullPath: '/codex/upgrades'
      preLoaderRoute: typeof CanvasCodexUpgradesRouteImport
      parentRoute: typeof CanvasRoute
    }
    '/_canvas/codex/modules/': {
      id: '/_canvas/codex/modules/'
      path: '/codex/modules'
      fullPath: '/codex/modules/'
      preLoaderRoute: typeof CanvasCodexModulesIndexRouteImport
      parentRoute: typeof CanvasRoute
    }
    '/_canvas/codex/modules/$moduleId': {
      id: '/_canvas/codex/modules/$moduleId'
      path: '/codex/modules/$moduleId'
      fullPath: '/codex/modules/$moduleId'
      preLoaderRoute: typeof CanvasCodexModulesModuleIdRouteImport
      parentRoute: typeof CanvasRoute
    }
  }
}

interface CanvasRouteChildren {
  CanvasIndexRoute: typeof CanvasIndexRoute
  CanvasCodexUpgradesRoute: typeof CanvasCodexUpgradesRoute
  CanvasPlayConfirmRouteRoute: typeof CanvasPlayConfirmRouteRoute
  CanvasPlaySelectRouteRoute: typeof CanvasPlaySelectRouteRoute
  CanvasPlaySelectShipRoute: typeof CanvasPlaySelectShipRoute
  CanvasPlayShipRoute: typeof CanvasPlayShipRoute
  CanvasCodexModulesModuleIdRoute: typeof CanvasCodexModulesModuleIdRoute
  CanvasCodexModulesIndexRoute: typeof CanvasCodexModulesIndexRoute
}

const CanvasRouteChildren: CanvasRouteChildren = {
  CanvasIndexRoute: CanvasIndexRoute,
  CanvasCodexUpgradesRoute: CanvasCodexUpgradesRoute,
  CanvasPlayConfirmRouteRoute: CanvasPlayConfirmRouteRoute,
  CanvasPlaySelectRouteRoute: CanvasPlaySelectRouteRoute,
  CanvasPlaySelectShipRoute: CanvasPlaySelectShipRoute,
  CanvasPlayShipRoute: CanvasPlayShipRoute,
  CanvasCodexModulesModuleIdRoute: CanvasCodexModulesModuleIdRoute,
  CanvasCodexModulesIndexRoute: CanvasCodexModulesIndexRoute,
}

const CanvasRouteWithChildren =
  CanvasRoute._addFileChildren(CanvasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  CanvasRoute: CanvasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
