import { BackgroundSceneArgs } from '../background-scene-args';
import { backgroundColorArgsCatalog } from './background-color-args-catalog';

export const backgroundSceneArgsCatalog = {
  orangeOnBlack: new BackgroundSceneArgs({
    actorColor: backgroundColorArgsCatalog.orange,
    backgroundColor: backgroundColorArgsCatalog.black,
    minSpeed: 20,
    maxSpeed: 120,
    minSize: 20,
    maxSize: 120,
    angleBase: 0,
    angleTolerance: 15,
  }),
  blackOnOrange: new BackgroundSceneArgs({
    actorColor: backgroundColorArgsCatalog.black,
    backgroundColor: backgroundColorArgsCatalog.orange,
    minSpeed: 10,
    maxSpeed: 120,
    minSize: 20,
    maxSize: 120,
    angleBase: 90,
    angleTolerance: 15,
  }),
  yellowOnPurple: new BackgroundSceneArgs({
    actorColor: backgroundColorArgsCatalog.yellow,
    backgroundColor: backgroundColorArgsCatalog.purple,
    minSpeed: 20,
    maxSpeed: 120,
    minSize: 20,
    maxSize: 120,
    angleBase: 180,
    angleTolerance: 15,
  }),
  cyanOnRed: new BackgroundSceneArgs({
    actorColor: backgroundColorArgsCatalog.cyan,
    backgroundColor: backgroundColorArgsCatalog.red,
    minSpeed: 20,
    maxSpeed: 120,
    minSize: 20,
    maxSize: 120,
    angleBase: 270,
    angleTolerance: 15,
  }),
  orangeOnBlue: new BackgroundSceneArgs({
    actorColor: backgroundColorArgsCatalog.orange,
    backgroundColor: backgroundColorArgsCatalog.blue,
    minSpeed: 20,
    maxSpeed: 120,
    minSize: 20,
    maxSize: 120,
    angleBase: 135,
    angleTolerance: 15,
  }),
  magentaOnBlack: new BackgroundSceneArgs({
    actorColor: backgroundColorArgsCatalog.magenta,
    backgroundColor: backgroundColorArgsCatalog.black,
    minSpeed: 20,
    maxSpeed: 120,
    minSize: 20,
    maxSize: 120,
    angleBase: 45,
    angleTolerance: 15,
  }),
  greenOnBlack: new BackgroundSceneArgs({
    actorColor: backgroundColorArgsCatalog.green,
    backgroundColor: backgroundColorArgsCatalog.black,
    minSpeed: 20,
    maxSpeed: 120,
    minSize: 20,
    maxSize: 120,
    angleBase: 315,
    angleTolerance: 15,
  }),
};
